apiVersion: v1
kind: Namespace
metadata:
  name: morpheus-csi
  labels:
    app.kubernetes.io/name: morpheus-csi
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
