apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: morpheus-storage
  labels:
    app.kubernetes.io/name: morpheus-csi
    app.kubernetes.io/component: storageclass
provisioner: csi.morpheusdata.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  morpheus.serverId: "replace-with-k8s-node-morpheus-server-id"
  morpheus.storageType: "38"
  morpheus.datastoreId: "replace-with-datastore-id"
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: morpheus-csi-credentials
  csi.storage.k8s.io/provisioner-secret-namespace: morpheus-csi
  csi.storage.k8s.io/controller-publish-secret-name: morpheus-csi-credentials
  csi.storage.k8s.io/controller-publish-secret-namespace: morpheus-csi
  csi.storage.k8s.io/node-stage-secret-name: morpheus-csi-credentials
  csi.storage.k8s.io/node-stage-secret-namespace: morpheus-csi
  csi.storage.k8s.io/node-publish-secret-name: morpheus-csi-credentials
  csi.storage.k8s.io/node-publish-secret-namespace: morpheus-csi
